In [2]:
%%bash

gppy txinfo -g "./ref/GCF_029169275.1_fixed.filtered.gtf" > "./metadata/Acer_txinfo.tsv"

In [3]:
from pyfaidx import Fasta

In [4]:
Acer_fa = Fasta('./ref/GCF_029169275.1_AcerK_1.0_genomic.fna')

In [6]:
for name in Acer_fa.keys():
    if name.startswith("NC"):
        print(f"{name}: {len(Acer_fa[name])}")

NC_083852.1: 27131825
NC_083853.1: 15875455
NC_083854.1: 13386827
NC_083855.1: 13159592
NC_083856.1: 13471485
NC_083857.1: 17285085
NC_083858.1: 13645534
NC_083859.1: 12170773
NC_083860.1: 11954044
NC_083861.1: 12434583
NC_083862.1: 15832348
NC_083863.1: 11302906
NC_083864.1: 11000381
NC_083865.1: 11731789
NC_083866.1: 9491825
NC_083867.1: 7109830
NC_014295.1: 15895

NC_014295.1 is mito

In [7]:
import pandas as pd

Acer_txinfo = pd.read_csv("./metadata/Acer_txinfo.tsv", sep = "\t")
Acer_txinfo

/tmp/ipykernel_56928/2544162422.py:3: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  Acer_txinfo = pd.read_csv("./metadata/Acer_txinfo.tsv", sep = "\t")

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,db_xref,exception,experiment,gbkey,gene,gene_biotype,inference,locus_tag,product,protein_id,transcript_biotype
0,XM_017048878.3,LOC107992807,NC_083852.1,-,6,713,312,197,204,GeneID:107992807,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992807,protein_coding,NaN,NaN,NaN,XP_016904367.1,mRNA
1,XM_017048879.3,LOC107992807,NC_083852.1,-,5,1167,312,651,204,GeneID:107992807,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992807,protein_coding,NaN,NaN,NaN,XP_016904368.1,mRNA
2,XM_062082541.1,LOC107992805,NC_083852.1,+,6,4095,3759,155,181,GeneID:107992805,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992805,protein_coding,NaN,NaN,NaN,XP_061938525.1,mRNA
3,XM_062082566.1,LOC107992805,NC_083852.1,+,7,4344,3717,446,181,GeneID:107992805,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992805,protein_coding,NaN,NaN,NaN,XP_061938550.1,mRNA
4,XM_062082576.1,LOC107992805,NC_083852.1,+,7,4339,3675,483,181,GeneID:107992805,NaN,COORDINATES: polyA evidence [ECO:0006239],mRNA,LOC107992805,protein_coding,NaN,NaN,NaN,XP_061938560.1,mRNA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34710,unassigned_transcript_252,KEH14_p05,NC_014295.1,-,1,1329,1329,0,0,NaN,NaN,NaN,mRNA,ND4,protein_coding,NaN,KEH14_p05,NaN,YP_003735177.1,mRNA
34711,unassigned_transcript_253,KEH14_p04,NC_014295.1,-,1,264,264,0,0,NaN,NaN,NaN,mRNA,ND4L,protein_coding,NaN,KEH14_p04,NaN,YP_003735178.1,mRNA
34712,unassigned_transcript_256,KEH14_p03,NC_014295.1,+,1,510,510,0,0,NaN,NaN,NaN,mRNA,ND6,protein_coding,NaN,KEH14_p03,NaN,YP_003735179.1,mRNA
34713,unassigned_transcript_257,KEH14_p02,NC_014295.1,+,1,1149,1149,0,0,NaN,NaN,NaN,mRNA,CYTB,protein_coding,NaN,KEH14_p02,NaN,YP_003735180.1,mRNA
34714,unassigned_transcript_259,KEH14_p01,NC_014295.1,-,1,915,915,0,0,NaN,NaN,NaN,mRNA,ND1,protein_coding,NaN,KEH14_p01,NaN,YP_003735181.1,mRNA

In [8]:
mito_txinfo = Acer_txinfo[Acer_txinfo["chrom"] == "NC_014295.1"]
mito_txinfo

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,db_xref,exception,experiment,gbkey,gene,gene_biotype,inference,locus_tag,product,protein_id,transcript_biotype
34702,unassigned_transcript_233,KEH14_p13,NC_014295.1,+,1,996,996,0,0,NaN,NaN,NaN,mRNA,ND2,protein_coding,NaN,KEH14_p13,NaN,YP_003735169.1,mRNA
34703,unassigned_transcript_237,KEH14_p12,NC_014295.1,+,1,1561,1561,0,0,NaN,NaN,NaN,mRNA,COX1,protein_coding,NaN,KEH14_p12,NaN,YP_003735170.2,mRNA
34704,unassigned_transcript_239,KEH14_p11,NC_014295.1,+,1,681,681,0,0,NaN,NaN,NaN,mRNA,COX2,protein_coding,NaN,KEH14_p11,NaN,YP_003735171.1,mRNA
34705,unassigned_transcript_242,KEH14_p10,NC_014295.1,+,1,162,162,0,0,NaN,NaN,NaN,mRNA,ATP8,protein_coding,NaN,KEH14_p10,NaN,YP_003735172.1,mRNA
34706,unassigned_transcript_243,KEH14_p09,NC_014295.1,+,1,678,678,0,0,NaN,NaN,NaN,mRNA,ATP6,protein_coding,NaN,KEH14_p09,NaN,YP_003735173.1,mRNA
34707,unassigned_transcript_244,KEH14_p08,NC_014295.1,+,1,780,780,0,0,NaN,NaN,NaN,mRNA,COX3,protein_coding,NaN,KEH14_p08,NaN,YP_003735174.1,mRNA
34708,unassigned_transcript_246,KEH14_p07,NC_014295.1,+,1,354,354,0,0,NaN,NaN,NaN,mRNA,ND3,protein_coding,NaN,KEH14_p07,NaN,YP_003735175.1,mRNA
34709,unassigned_transcript_250,KEH14_p06,NC_014295.1,-,1,1671,1671,0,0,NaN,NaN,NaN,mRNA,ND5,protein_coding,NaN,KEH14_p06,NaN,YP_003735176.1,mRNA
34710,unassigned_transcript_252,KEH14_p05,NC_014295.1,-,1,1329,1329,0,0,NaN,NaN,NaN,mRNA,ND4,protein_coding,NaN,KEH14_p05,NaN,YP_003735177.1,mRNA
34711,unassigned_transcript_253,KEH14_p04,NC_014295.1,-,1,264,264,0,0,NaN,NaN,NaN,mRNA,ND4L,protein_coding,NaN,KEH14_p04,NaN,YP_003735178.1,mRNA
34712,unassigned_transcript_256,KEH14_p03,NC_014295.1,+,1,510,510,0,0,NaN,NaN,NaN,mRNA,ND6,protein_coding,NaN,KEH14_p03,NaN,YP_003735179.1,mRNA
34713,unassigned_transcript_257,KEH14_p02,NC_014295.1,+,1,1149,1149,0,0,NaN,NaN,NaN,mRNA,CYTB,protein_coding,NaN,KEH14_p02,NaN,YP_003735180.1,mRNA
34714,unassigned_transcript_259,KEH14_p01,NC_014295.1,-,1,915,915,0,0,NaN,NaN,NaN,mRNA,ND1,protein_coding,NaN,KEH14_p01,NaN,YP_003735181.1,mRNA

In [9]:
mito_txinfo_geneid = set(mito_txinfo["gene_id"].to_list())
mito_txinfo_geneid

{'KEH14_p01',
 'KEH14_p02',
 'KEH14_p03',
 'KEH14_p04',
 'KEH14_p05',
 'KEH14_p06',
 'KEH14_p07',
 'KEH14_p08',
 'KEH14_p09',
 'KEH14_p10',
 'KEH14_p11',
 'KEH14_p12',
 'KEH14_p13'}

In [11]:
import scanpy as sc

adata = sc.read_10x_h5("./h5_from_fastq2matrix/drone_rep1_singlet.h5")

In [12]:
adata.var

                  gene_ids    feature_types           genome
LOC107992807  LOC107992807  Gene Expression  A_cer_mkref_out
LOC107992805  LOC107992805  Gene Expression  A_cer_mkref_out
LOC107992806  LOC107992806  Gene Expression  A_cer_mkref_out
LOC107992868  LOC107992868  Gene Expression  A_cer_mkref_out
LOC107992792  LOC107992792  Gene Expression  A_cer_mkref_out
...                    ...              ...              ...
KEH14_p05        KEH14_p05  Gene Expression  A_cer_mkref_out
KEH14_p04        KEH14_p04  Gene Expression  A_cer_mkref_out
KEH14_p03        KEH14_p03  Gene Expression  A_cer_mkref_out
KEH14_p02        KEH14_p02  Gene Expression  A_cer_mkref_out
KEH14_p01        KEH14_p01  Gene Expression  A_cer_mkref_out

[12561 rows x 3 columns]

In [13]:
var_names_set = set(adata.var_names)
gene_ids_set = set(adata.var["gene_ids"].to_list())

print(len(var_names_set & mito_txinfo_geneid))
print(len(gene_ids_set & mito_txinfo_geneid))

13
13

In [14]:
mito_txinfo["gene_id"].to_csv("./metadata/mito.txt", header=False, index=False)