In [7]:
%%bash

gppy txinfo -g "./ref/Apis_mellifera.Amel_HAv3.1.62.filtered.gtf" > ./metadata/Amel_txinfo.tsv

- First, use gppy to convert the GTF file to TSV, and determine which `gene_id` correspond to the `chrom` of the mitochondria.
- In adata.var, create a new column "mt", and mark the genes belonging to mitochondria in adata.var.gene_ids as True.

In [2]:
from pyfaidx import Fasta

In [3]:
Amel_fa = Fasta('./ref/Apis_mellifera.Amel_HAv3.1.dna.toplevel.fa')

In [4]:
for name in Amel_fa.keys():
    if name.startswith("CM"):
        print(f"{name}: {len(Amel_fa[name])}")

CM009931.2: 27754200
CM009932.2: 16089512
CM009933.2: 13619445
CM009934.2: 13404451
CM009935.2: 13896941
CM009936.2: 17789102
CM009937.2: 14198698
CM009938.2: 12717210
CM009939.2: 12354651
CM009940.2: 12360052
CM009941.2: 16352600
CM009942.2: 11514234
CM009943.2: 11279722
CM009944.2: 10670842
CM009945.2: 9534514
CM009946.2: 7238532
CM009947.2: 16343

CM009947.2 is mito

In [8]:
import pandas as pd

Amel_txinfo = pd.read_csv("./metadata/Amel_txinfo.tsv", sep = "\t")
Amel_txinfo

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,gene_biotype,gene_name,gene_source,protein_id,transcript_biotype,transcript_name,transcript_source,ensembl_canonical,seleno
0,XM_006559882,LOC100576147,CM009931.2,+,1,4102,1278,520,2304,protein_coding,NaN,RefSeq,XP_006559945,protein_coding,NaN,RefSeq,True,False
1,XM_006561922,LOC100577342,CM009931.2,+,4,1173,825,192,156,protein_coding,NaN,RefSeq,XP_006561985,protein_coding,NaN,RefSeq,True,False
2,XM_026445023,LOC551556,CM009931.2,-,4,1369,1209,122,38,protein_coding,NaN,RefSeq,XP_026300808,protein_coding,NaN,RefSeq,True,False
3,XM_006563296,LOC727596,CM009931.2,+,4,1065,807,199,59,protein_coding,NaN,RefSeq,XP_006563359,protein_coding,NaN,RefSeq,True,False
4,XM_026446341,LOC727596,CM009931.2,+,5,1018,807,152,59,protein_coding,NaN,RefSeq,XP_026302126,protein_coding,NaN,RefSeq,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27549,XR_003306463,LOC113219386,QIUM02000194.1,+,4,572,0,0,0,lncRNA,NaN,RefSeq,NaN,lncRNA,NaN,RefSeq,False,False
27550,XR_003306467,LOC113219386,QIUM02000194.1,+,4,485,0,0,0,lncRNA,NaN,RefSeq,NaN,lncRNA,NaN,RefSeq,False,False
27551,XR_003306465,LOC113219386,QIUM02000194.1,+,4,483,0,0,0,lncRNA,NaN,RefSeq,NaN,lncRNA,NaN,RefSeq,False,False
27552,XR_003306464,LOC113219386,QIUM02000194.1,+,4,604,0,0,0,lncRNA,NaN,RefSeq,NaN,lncRNA,NaN,RefSeq,True,False
27553,XM_026445952,LOC113219358,QIUM02000217.1,-,2,888,504,0,384,protein_coding,NaN,RefSeq,XP_026301737,protein_coding,NaN,RefSeq,True,False

In [9]:
mito_txinfo = Amel_txinfo[Amel_txinfo["chrom"] == "CM009947.2"]
mito_txinfo

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,gene_biotype,gene_name,gene_source,protein_id,transcript_biotype,transcript_name,transcript_source,ensembl_canonical,seleno
27348,GeneID_807695_df_mr,GeneID_807695,CM009947.2,+,1,1566,1566,0,0,protein_coding,COX1,RefSeq,NP_008083,protein_coding,COX1_df_mr,RefSeq,True,False
27349,GeneID_807696_df_mr,GeneID_807696,CM009947.2,+,1,681,681,0,0,protein_coding,ATP6,RefSeq,NP_008086,protein_coding,ATP6_df_mr,RefSeq,True,False
27350,GeneID_807699_df_mr,GeneID_807699,CM009947.2,+,1,159,159,0,0,protein_coding,ATP8,RefSeq,NP_008085,protein_coding,ATP8_df_mr,RefSeq,True,False
27351,GeneID_807700_df_mr,GeneID_807700,CM009947.2,+,1,678,678,0,0,protein_coding,COX2,RefSeq,NP_008084,protein_coding,COX2_df_mr,RefSeq,True,False
27352,GeneID_807690_df_mr,GeneID_807690,CM009947.2,+,1,780,780,0,0,protein_coding,COX3,RefSeq,NP_008087,protein_coding,COX3_df_mr,RefSeq,True,False
27353,GeneID_807702_df_mr,GeneID_807702,CM009947.2,-,1,1344,1344,0,0,protein_coding,ND4,RefSeq,NP_008090,protein_coding,ND4_df_mr,RefSeq,True,False
27354,GeneID_807693_df_mr,GeneID_807693,CM009947.2,+,1,1152,1152,0,0,protein_coding,CYTB,RefSeq,NP_008093,protein_coding,CYTB_df_mr,RefSeq,True,False
27355,GeneID_807692_df_mr,GeneID_807692,CM009947.2,-,1,918,918,0,0,protein_coding,ND1,RefSeq,NP_008094,protein_coding,ND1_df_mr,RefSeq,True,False
27356,GeneID_807698_df_mr,GeneID_807698,CM009947.2,-,1,1665,1665,0,0,protein_coding,ND5,RefSeq,NP_008089,protein_coding,ND5_df_mr,RefSeq,True,False
27357,GeneID_807701_df_mr,GeneID_807701,CM009947.2,+,1,1002,1002,0,0,protein_coding,ND2,RefSeq,NP_008082,protein_coding,ND2_df_mr,RefSeq,True,False
27358,GeneID_807691_df_mr,GeneID_807691,CM009947.2,+,1,354,354,0,0,protein_coding,ND3,RefSeq,NP_008088,protein_coding,ND3_df_mr,RefSeq,True,False
27359,GeneID_807697_df_mr,GeneID_807697,CM009947.2,+,1,504,504,0,0,protein_coding,ND6,RefSeq,NP_008092,protein_coding,ND6_df_mr,RefSeq,True,False
27360,GeneID_807694_df_mr,GeneID_807694,CM009947.2,-,1,264,264,0,0,protein_coding,ND4L,RefSeq,NP_008091,protein_coding,ND4L_df_mr,RefSeq,True,False

In [10]:
mito_txinfo_geneid = set(mito_txinfo["gene_id"].to_list())
mito_txinfo_geneid

{'GeneID_807690',
 'GeneID_807691',
 'GeneID_807692',
 'GeneID_807693',
 'GeneID_807694',
 'GeneID_807695',
 'GeneID_807696',
 'GeneID_807697',
 'GeneID_807698',
 'GeneID_807699',
 'GeneID_807700',
 'GeneID_807701',
 'GeneID_807702'}

In [40]:
import scanpy as sc

F1_adata = sc.read_10x_h5("./h5_from_fastq2matrix/F1.h5")

/home/liuzhiyu/Software/miniconda3/envs/downstream_analysis/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/liuzhiyu/Software/miniconda3/envs/downstream_analysis/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [41]:
F1_adata.var

                  gene_ids    feature_types           genome
LOC100576147  LOC100576147  Gene Expression  A_mel_mkref_out
LOC100577342  LOC100577342  Gene Expression  A_mel_mkref_out
LOC551556        LOC551556  Gene Expression  A_mel_mkref_out
LOC727596        LOC727596  Gene Expression  A_mel_mkref_out
LOC102653881  LOC102653881  Gene Expression  A_mel_mkref_out
...                    ...              ...              ...
LOC113219384  LOC113219384  Gene Expression  A_mel_mkref_out
LOC107965808  LOC107965808  Gene Expression  A_mel_mkref_out
LOC113219385  LOC113219385  Gene Expression  A_mel_mkref_out
LOC113219386  LOC113219386  Gene Expression  A_mel_mkref_out
LOC113219358  LOC113219358  Gene Expression  A_mel_mkref_out

[11793 rows x 3 columns]

In [35]:
F1_var_names_set = set(F1_adata.var_names)
F1_gene_ids_set = set(F1_adata.var["gene_ids"].to_list())

print(len(F1_var_names_set & mito_txinfo_geneid))
print(len(F1_gene_ids_set & mito_txinfo_geneid))

0
13

In [43]:
F1_adata.var[F1_adata.var["gene_ids"] == "GeneID_807693"]

           gene_ids    feature_types           genome
CYTB  GeneID_807693  Gene Expression  A_mel_mkref_out

In [12]:
F1_geneids = set(F1_adata.var["gene_ids"].to_list())
F1_geneids

{'LOC552513',
 'GeneID_552033',
 'LOC107965672',
 'LOC551904',
 'LOC102653810',
 'LOC413759',
 'LOC413447',
 'LOC100576783',
 'LOC727592',
 'LOC409899',
 'LOC726546',
 'LOC410872',
 'LOC411699',
 'LOC412357',
 'LOC100578752',
 'LOC724243',
 'LOC107963981',
 'LOC413332',
 'LOC100578445',
 'GeneID_100577371',
 'LOC410231',
 'LOC726801',
 'LOC551948',
 'LOC102655976',
 'LOC725950',
 'LOC408969',
 'LOC412931',
 'LOC107964460',
 'LOC102654549',
 'LOC100576104',
 'LOC725515',
 'LOC551631',
 'LOC409787',
 'LOC724487',
 'LOC413399',
 'LOC725736',
 'GeneID_726182',
 'LOC725053',
 'LOC100577407',
 'LOC411411',
 'LOC100578751',
 'LOC726361',
 'LOC113218592',
 'LOC100578649',
 'LOC113218748',
 'LOC411697',
 'LOC411468',
 'LOC100576878',
 'LOC725793',
 'LOC113219043',
 'LOC102656472',
 'LOC100577777',
 'LOC413558',
 'LOC551538',
 'LOC412913',
 'LOC412295',
 'GeneID_408855',
 'LOC100578337',
 'LOC552019',
 'LOC409389',
 'LOC113219125',
 'LOC100577587',
 'LOC113218609',
 'LOC102654528',
 'LOC411490',
 'LOC727515',
 'GeneID_406127',
 'LOC409841',
 'LOC725151',
 'LOC725125',
 'LOC409908',
 'LOC107965235',
 'LOC100577667',
 'LOC408339',
 'LOC411183',
 'LOC102655407',
 'LOC552732',
 'LOC102656398',
 'LOC727238',
 'LOC413502',
 'LOC102654917',
 'LOC409395',
 'LOC413746',
 'LOC550992',
 'LOC413134',
 'LOC113218805',
 'LOC107963977',
 'LOC724749',
 'GeneID_724970',
 'LOC412306',
 'LOC411793',
 'GeneID_408399',
 'LOC100577428',
 'LOC726803',
 'LOC409068',
 'LOC409169',
 'LOC551799',
 'LOC412107',
 'LOC410019',
 'LOC113218733',
 'LOC727398',
 'LOC724464',
 'LOC102656387',
 'LOC100576289',
 'LOC551982',
 'LOC107965260',
 'LOC107964072',
 'LOC100576808',
 'LOC725551',
 'LOC552675',
 'LOC409173',
 'LOC726879',
 'LOC100578614',
 'LOC100578978',
 'LOC100577288',
 'LOC100578391',
 'GeneID_551971',
 'LOC410980',
 'LOC100578428',
 'GeneID_100577031',
 'LOC102653795',
 'LOC725317',
 'LOC100578881',
 'LOC552139',
 'LOC113219236',
 'LOC726646',
 'LOC100577751',
 'GeneID_551341',
 'LOC551845',
 'LOC102655339',
 'LOC102655243',
 'LOC102654728',
 'LOC107964872',
 'GeneID_408270',
 'LOC552403',
 'LOC725934',
 'LOC724117',
 'LOC102656657',
 'LOC724855',
 'LOC552279',
 'LOC113218536',
 'LOC551130',
 'LOC412141',
 'LOC102656488',
 'LOC113218743',
 'LOC100578854',
 'LOC726250',
 'LOC725609',
 'LOC410102',
 'LOC100578354',
 'LOC726368',
 'LOC410706',
 'LOC552318',
 'LOC411555',
 'LOC100576304',
 'LOC102656571',
 'LOC410289',
 'LOC100577810',
 'LOC412397',
 'LOC107965271',
 'LOC725727',
 'LOC100578378',
 'LOC107965102',
 'LOC102656508',
 'LOC412865',
 'LOC551660',
 'LOC100578586',
 'LOC725346',
 'LOC724531',
 'LOC100577889',
 'LOC552260',
 'LOC725963',
 'GeneID_411659',
 'LOC100577286',
 'LOC100577661',
 'LOC102655232',
 'LOC413275',
 'LOC412541',
 'LOC408708',
 'LOC411758',
 'LOC102656274',
 'LOC102653804',
 'LOC408402',
 'LOC113218521',
 'LOC107964493',
 'LOC102654758',
 'LOC102656773',
 'LOC552433',
 'LOC552534',
 'LOC552003',
 'LOC107964845',
 'LOC412495',
 'LOC410387',
 'LOC409038',
 'GeneID_408363',
 'LOC412056',
 'LOC107964905',
 'LOC726672',
 'LOC113218764',
 'LOC550818',
 'LOC551711',
 'LOC412148',
 'LOC552467',
 'LOC552771',
 'LOC724393',
 'GeneID_406103',
 'LOC100577141',
 'LOC102655391',
 'LOC413494',
 'LOC100578746',
 'LOC100576794',
 'LOC107964743',
 'LOC113218637',
 'LOC552485',
 'LOC107965670',
 'LOC102654159',
 'LOC726728',
 'LOC113218896',
 'LOC725234',
 'LOC727055',
 'LOC411658',
 'LOC412408',
 'LOC413056',
 'LOC410894',
 'LOC725798',
 'LOC550698',
 'LOC100576467',
 'LOC411822',
 'LOC552147',
 'LOC724443',
 'LOC411683',
 'LOC551658',
 'LOC413118',
 'LOC408934',
 'LOC552469',
 'LOC412570',
 'LOC107965218',
 'LOC100187599',
 'LOC102655568',
 'LOC100578090',
 'LOC409517',
 'LOC552677',
 'LOC100576472',
 'LOC409826',
 'LOC726189',
 'LOC413623',
 'LOC100576623',
 'LOC724477',
 'LOC100579018',
 'LOC726096',
 'LOC102655779',
 'LOC726977',
 'LOC726589',
 'LOC100578200',
 'LOC107963999',
 'LOC724817',
 'LOC413400',
 'LOC113218597',
 'LOC100578443',
 'LOC552593',
 'LOC102656218',
 'LOC724876',
 'LOC413450',
 'LOC725829',
 'LOC100579021',
 'LOC727025',
 'LOC113219231',
 'LOC412007',
 'LOC102654091',
 'LOC411694',
 'LOC552516',
 'LOC726056',
 'LOC409934',
 'LOC551080',
 'LOC551345',
 'LOC727012',
 'LOC411591',
 'LOC551447',
 'LOC413812',
 'LOC410296',
 'LOC551668',
 'LOC102656308',
 'LOC100578885',
 'LOC107964068',
 'LOC100577836',
 'LOC113218923',
 'LOC102655427',
 'LOC102655787',
 'LOC411611',
 'LOC100576896',
 'LOC100576505',
 'LOC412375',
 'LOC551731',
 'LOC411090',
 'GeneID_409940',
 'LOC727418',
 'LOC552807',
 'LOC102655292',
 'LOC408564',
 'LOC107964911',
 'LOC409137',
 'LOC726147',
 'LOC113219114',
 'LOC410889',
 'LOC725393',
 'LOC726225',
 'LOC410649',
 'LOC411288',
 'LOC100577398',
 'LOC102654579',
 'LOC727346',
 'LOC100578909',
 'LOC725455',
 'LOC411223',
 'LOC100578014',
 'LOC412768',
 'LOC409301',
 'LOC551844',
 'LOC552282',
 'LOC551986',
 'LOC102654214',
 'LOC102655824',
 'LOC724529',
 'LOC410961',
 'LOC727612',
 'LOC551682',
 'LOC552346',
 'LOC550924',
 'LOC552062',
 'LOC412544',
 'LOC727157',
 'LOC412550',
 'LOC409633',
 'LOC550664',
 'LOC102655674',
 'LOC409143',
 'LOC408333',
 'LOC726643',
 'LOC107965676',
 'LOC411639',
 'LOC552663',
 'LOC409186',
 'LOC408785',
 'LOC727436',
 'LOC413293',
 'LOC100578739',
 'LOC409778',
 'LOC113218858',
 'GeneID_409469',
 'LOC412823',
 'LOC113218630',
 'LOC107964214',
 'LOC100576944',
 'LOC100577584',
 'LOC413274',
 'LOC552277',
 'LOC100578666',
 'LOC552488',
 'LOC410753',
 'GeneID_100577714',
 'LOC113218760',
 'LOC552085',
 'LOC552153',
 'LOC410581',
 'LOC102655862',
 'LOC410952',
 'LOC113218674',
 'LOC413152',
 'LOC725923',
 'LOC552612',
 'LOC408811',
 'LOC100577071',
 'LOC409355',
 'LOC724440',
 'LOC100577908',
 'LOC727311',
 'LOC107963996',
 'LOC107964769',
 'LOC102655555',
 'LOC413885',
 'LOC725844',
 'LOC725102',
 'LOC409046',
 'LOC412529',
 'LOC102654976',
 'LOC102655603',
 'LOC107965063',
 'LOC102654729',
 'LOC113218963',
 'LOC551683',
 'LOC412681',
 'LOC411843',
 'LOC410446',
 'LOC552072',
 'LOC725618',
 'LOC727524',
 'LOC100576615',
 'GeneID_409948',
 'LOC113219361',
 'LOC410307',
 'LOC100578694',
 'LOC725345',
 'LOC551839',
 'LOC725973',
 'LOC410614',
 'LOC100576502',
 'LOC409799',
 'LOC410936',
 'LOC100578826',
 'LOC724860',
 'LOC411627',
 'LOC552016',
 'LOC102656882',
 'LOC550695',
 'LOC409953',
 'LOC100577644',
 'LOC726061',
 'LOC724756',
 'LOC102655536',
 'LOC107964400',
 'LOC409983',
 'LOC411846',
 'LOC552236',
 'LOC100576532',
 'LOC552331',
 'LOC408818',
 'LOC113219372',
 'LOC410501',
 'LOC406073',
 'LOC100578113',
 'LOC102655849',
 'LOC100577548',
 'LOC113218749',
 'LOC552530',
 'LOC102654245',
 'LOC100577041',
 'LOC100576382',
 'LOC724877',
 'LOC102654231',
 'LOC102656523',
 'LOC726650',
 'LOC726219',
 'LOC412679',
 'LOC726149',
 'LOC100577606',
 'LOC725572',
 'LOC725196',
 'LOC409822',
 'LOC551499',
 'LOC102654905',
 'LOC413919',
 'LOC100577452',
 'LOC100576975',
 'LOC726890',
 'LOC551636',
 'LOC100576291',
 'LOC411958',
 'LOC726671',
 'LOC410191',
 'LOC725444',
 'LOC552426',
 'LOC412638',
 'LOC410006',
 'LOC113218873',
 'LOC724252',
 'LOC102655134',
 'LOC410862',
 'LOC408398',
 'LOC102655009',
 'LOC409557',
 'LOC100576242',
 'LOC413223',
 'LOC551560',
 'LOC107964864',
 'LOC100577573',
 'LOC552417',
 'LOC113219112',
 'LOC725700',
 'LOC725409',
 'LOC726983',
 'LOC100577949',
 'LOC411214',
 'LOC412543',
 'LOC409613',
 'LOC107965175',
 'LOC550710',
 'LOC411569',
 'LOC113218580',
 'LOC100578879',
 'LOC410229',
 'LOC725817',
 'LOC552798',
 'LOC410316',
 'LOC413785',
 'LOC413534',
 'LOC725671',
 'LOC411507',
 'LOC724769',
 'GeneID_410902',
 'LOC408988',
 'LOC100577074',
 'LOC725365',
 'LOC410879',
 'LOC551474',
 'LOC102654351',
 'LOC411622',
 'LOC102654030',
 'LOC726282',
 'LOC411206',
 'LOC725197',
 'LOC552733',
 'LOC113218922',
 'LOC726297',
 'LOC100577516',
 'LOC725756',
 'LOC411718',
 'LOC107965727',
 'LOC411013',
 'LOC107966099',
 'LOC100578413',
 'LOC409647',
 'LOC552577',
 'LOC724240',
 'LOC100577697',
 'LOC100576855',
 'LOC408705',
 'LOC100577981',
 'LOC552232',
 'LOC412924',
 'LOC552576',
 'LOC100577693',
 'LOC724241',
 'LOC725903',
 'LOC100578611',
 'LOC102655124',
 'LOC102655679',
 'LOC102655778',
 'LOC725887',
 'LOC412371',
 'LOC410819',
 'LOC411649',
 'LOC107965256',
 'LOC724152',
 'LOC102655028',
 'LOC100577680',
 'LOC551119',
 'LOC727310',
 'LOC411691',
 'LOC725578',
 'LOC100576452',
 'LOC102654465',
 'LOC100577436',
 'LOC107965406',
 'LOC113219230',
 'LOC412526',
 'GeneID_552391',
 'LOC725122',
 'LOC751767',
 'LOC409019',
 'LOC410688',
 'LOC412984',
 'LOC552665',
 'LOC552067',
 'GeneID_503862',
 'LOC409956',
 'LOC409972',
 'LOC552326',
 'LOC409110',
 'LOC113219299',
 'LOC100578745',
 'LOC725830',
 'LOC100577053',
 'LOC107964742',
 'LOC726458',
 'LOC725991',
 'LOC550748',
 'LOC102653851',
 'LOC410539',
 'LOC412487',
 'LOC724811',
 'LOC552728',
 'LOC100578126',
 'LOC412116',
 'LOC551177',
 'LOC107964737',
 'LOC409968',
 'LOC725591',
 'LOC102654353',
 'LOC100576621',
 'LOC113219104',
 'LOC100577466',
 'LOC724385',
 'LOC100578782',
 'GeneID_807697',
 'LOC412630',
 'LOC107965534',
 'LOC413714',
 'LOC102654781',
 'LOC411104',
 'GeneID_406119',
 'LOC724250',
 'LOC113219145',
 'LOC100578811',
 'LOC102656496',
 'LOC413194',
 'LOC727091',
 'LOC100576820',
 'LOC107964820',
 'GeneID_100328599',
 'LOC725209',
 'LOC724617',
 'LOC102654085',
 'LOC113219352',
 'LOC102655311',
 'LOC726883',
 'LOC725284',
 'LOC552662',
 'LOC409099',
 'LOC409624',
 'LOC410013',
 'LOC725047',
 'LOC727431',
 'LOC726860',
 'LOC113219291',
 'LOC551924',
 'LOC107966088',
 'LOC412009',
 'LOC552429',
 'LOC726444',
 'LOC725616',
 'LOC409487',
 'LOC408970',
 'LOC107965873',
 'LOC412384',
 'LOC113219229',
 'LOC100577382',
 'LOC727118',
 'LOC100576374',
 'LOC102653693',
 'LOC411502',
 'LOC100576534',
 'LOC409546',
 'LOC107965616',
 'GeneID_409779',
 'LOC552489',
 'LOC410607',
 'LOC725883',
 'LOC412825',
 'LOC102653834',
 'GeneID_725996',
 'LOC410673',
 'LOC409463',
 'LOC409501',
 'LOC413076',
 'LOC726914',
 'LOC107966112',
 'LOC411806',
 'GeneID_409042',
 'LOC113219050',
 'LOC551666',
 'GeneID_544670',
 'LOC409999',
 'LOC726218',
 'LOC102656871',
 'LOC551539',
 'LOC102654542',
 'LOC107964645',
 'LOC408293',
 'LOC410990',
 'LOC551073',
 'LOC552546',
 'LOC100577132',
 'LOC409888',
 'LOC100578584',
 'LOC724391',
 'LOC107964467',
 'LOC409306',
 'LOC100578526',
 'LOC409361',
 'LOC552694',
 'LOC409608',
 'LOC725068',
 'LOC725238',
 'LOC412647',
 'LOC100578988',
 'LOC726460',
 'LOC113218655',
 'LOC552845',
 'LOC408369',
 'LOC100577520',
 'LOC102656788',
 'LOC411930',
 'LOC411785',
 'LOC100576164',
 'LOC724244',
 'LOC102654246',
 'LOC113219328',
 'LOC412240',
 'LOC551980',
 'LOC113219337',
 'LOC550645',
 'LOC107963971',
 'LOC409693',
 'LOC726139',
 'LOC107964797',
 'LOC408646',
 'GeneID_724556',
 'LOC102656071',
 'LOC100578651',
 'LOC408443',
 'LOC552569',
 'LOC100576916',
 'LOC552234',
 'LOC552007',
 'LOC100577222',
 'LOC550799',
 'LOC413490',
 'LOC412430',
 'LOC107965701',
 'LOC552096',
 'LOC409969',
 'LOC724705',
 'LOC724740',
 'LOC113218879',
 'LOC107965253',
 'LOC551043',
 'LOC102654144',
 'GeneID_408956',
 'LOC107964914',
 'LOC409653',
 'LOC412117',
 'LOC100576370',
 'LOC725119',
 'LOC551373',
 'LOC410257',
 'LOC410237',
 'LOC113218965',
 'LOC100578558',
 'LOC102654184',
 'LOC411802',
 'LOC113218830',
 'LOC100576958',
 'LOC726150',
 'LOC409843',
 'LOC410483',
 'LOC409603',
 'LOC113219059',
 'LOC113219159',
 'LOC107965706',
 'LOC102655523',
 'GeneID_724649',
 'LOC552401',
 'LOC411197',
 'LOC102656724',
 'LOC413527',
 'LOC724761',
 'LOC100578106',
 'LOC411448',
 'LOC113218869',
 'LOC409688',
 'LOC100576153',
 'LOC725127',
 'LOC113219414',
 'LOC113218742',
 'LOC551093',
 'LOC113218744',
 'LOC409752',
 'LOC408877',
 'LOC113219243',
 'LOC113219298',
 'LOC408578',
 'LOC724924',
 'LOC102656608',
 'LOC725784',
 'LOC409863',
 'LOC107964868',
 'LOC550869',
 'LOC412100',
 'LOC725607',
 'LOC725439',
 'LOC411495',
 'LOC552836',
 'LOC410621',
 'LOC724293',
 'LOC724287',
 'LOC113219189',
 'LOC552592',
 'GeneID_406090',
 'LOC725993',
 'LOC102654134',
 'LOC100578507',
 'LOC727223',
 'LOC726389',
 'LOC100578394',
 'LOC727030',
 'LOC100578680',
 'LOC410610',
 'LOC726392',
 'LOC100577578',
 'LOC726118',
 'LOC113218564',
 'LOC408531',
 'LOC100578777',
 'LOC726955',
 'LOC725733',
 'LOC102655240',
 'LOC727205',
 'LOC552071',
 'LOC102653847',
 'LOC408733',
 'LOC725946',
 'LOC100576085',
 'LOC726463',
 'LOC725492',
 'LOC552065',
 'LOC726742',
 'LOC100578943',
 'LOC113218824',
 'LOC409891',
 'LOC552605',
 'LOC100578780',
 'LOC100577028',
 'LOC102656592',
 'LOC726513',
 'LOC410299',
 'LOC408494',
 'LOC412212',
 'LOC409525',
 'LOC107965474',
 'LOC100578512',
 'LOC727582',
 'LOC102655463',
 'LOC726613',
 'LOC113219117',
 'LOC411861',
 'LOC412199',
 'LOC100576848',
 'LOC409718',
 'LOC725678',
 'LOC408724',
 'LOC100577476',
 'LOC102656556',
 'GeneID_409345',
 'LOC725580',
 'LOC724808',
 'LOC102655519',
 'LOC100578129',
 'LOC724962',
 'LOC411175',
 'LOC100577995',
 'LOC552317',
 'LOC408508',
 'LOC726496',
 'LOC113219412',
 'LOC413314',
 'LOC102656656',
 'LOC411712',
 'LOC552371',
 'LOC412780',
 'LOC100577164',
 'LOC409170',
 'LOC102654521',
 'GeneID_807693',
 'LOC725217',
 'LOC100576597',
 'LOC113219194',
 'LOC102656905',
 'LOC102655148',
 'LOC410031',
 'LOC725945',
 'GeneID_406134',
 'LOC409538',
 'LOC725067',
 'LOC412401',
 'LOC410870',
 'LOC410994',
 'LOC102654272',
 'LOC102655690',
 'LOC100578121',
 'LOC100576212',
 'LOC724639',
 'LOC413285',
 'LOC408864',
 'LOC409617',
 'LOC551914',
 'LOC551508',
 'LOC107965279',
 'LOC726880',
 'LOC726815',
 'LOC100576517',
 'LOC726525',
 'LOC410343',
 'LOC726504',
 'LOC100577875',
 'LOC100577455',
 'LOC724221',
 'LOC725099',
 'LOC102655355',
 'LOC413404',
 'LOC408477',
 'LOC412923',
 'GeneID_100642168',
 'LOC409231',
 'LOC410005',
 'LOC102654387',
 'LOC100576433',
 'LOC102655785',
 'LOC552266',
 'LOC107965289',
 'LOC409088',
 'LOC412003',
 'LOC100576902',
 'LOC552503',
 'LOC113218750',
 'LOC552772',
 'LOC411265',
 'LOC552723',
 'LOC412355',
 'LOC100576522',
 'LOC102654314',
 'LOC410993',
 'LOC413245',
 'LOC726375',
 'LOC410264',
 'GeneID_100577902',
 'LOC100576644',
 'LOC113219073',
 'LOC102654638',
 'LOC411595',
 'LOC102654380',
 'LOC107965080',
 'LOC408544',
 'LOC725496',
 'LOC107965483',
 'GeneID_410681',
 'LOC100578514',
 'LOC107964651',
 'LOC113218992',
 'LOC413693',
 'LOC100576989',
 'LOC102654652',
 'LOC725218',
 'LOC409109',
 'LOC409091',
 'LOC552451',
 'LOC725574',
 'LOC100577918',
 'LOC410340',
 'LOC725699',
 'LOC100577231',
 'LOC724727',
 'GeneID_100578127',
 'LOC100577106',
 'LOC408722',
 'LOC412093',
 'LOC410780',
 'LOC100577320',
 'LOC411301',
 'LOC725734',
 'LOC107964319',
 'LOC113218738',
 'LOC100577174',
 'LOC551957',
 'LOC724928',
 'LOC412077',
 'LOC107963972',
 'LOC100577559',
 'LOC726522',
 'LOC410094',
 'LOC410623',
 'LOC552043',
 'LOC408604',
 'GeneID_412285',
 'LOC726544',
 'LOC100577723',
 'LOC413720',
 'LOC551662',
 'LOC100578572',
 'LOC410201',
 'LOC551771',
 'LOC107964649',
 'LOC412341',
 'LOC100578404',
 'LOC100577641',
 'LOC102656725',
 'LOC102653658',
 'LOC107964408',
 'LOC550827',
 'LOC100576165',
 'LOC413727',
 'LOC409108',
 'LOC102656779',
 'LOC100578890',
 'LOC726274',
 'LOC413875',
 'LOC409127',
 'LOC552322',
 'LOC113219128',
 'LOC552509',
 'LOC113218519',
 ...}

In [13]:
print(len(mito_txinfo_geneid & F1_geneids))
print(mito_txinfo_geneid & F1_geneids)

13
{'GeneID_807695', 'GeneID_807696', 'GeneID_807701', 'GeneID_807694', 'GeneID_807692', 'GeneID_807698', 'GeneID_807690', 'GeneID_807693', 'GeneID_807691', 'GeneID_807699', 'GeneID_807700', 'GeneID_807702', 'GeneID_807697'}

↑ The F1 Anndata contains 13 mitochondrial genes. Same as `/data/share/data/Zhou_lab_seq_data/20251022_scRNA_lzy/1_LZU/check_mt.py`

In the expression matrix provided by `Zhang et al., 2022`, nearly 450 genes were labeled as `mt` in a single Anndata object, <mark style="background: #FF5582A6;">which is an error in their workflow.</mark>:

![image](../.image/iscience_mito.png)

Save mito gene_id as txt

This file will be used in QC process:

In [5]:
mito_txinfo["gene_id"].to_csv("./metadata/mito.txt", header=False, index=False)