In [2]:
%%bash

gppy txinfo -g ./ref/Apis_mellifera.Amel_HAv3.1.62.gtf > ./metadata/Amel_txinfo.tsv

- First, use gppy to convert the GTF file to TSV, and determine which `gene_id` correspond to the `chrom` of the mitochondria.
- In adata.var, create a new column "mt", and mark the genes belonging to mitochondria in adata.var.gene_ids as True.

In [3]:
from pyfaidx import Fasta

In [4]:
Amel_fa = Fasta('./ref/Apis_mellifera.Amel_HAv3.1.dna.toplevel.fa')

In [ ]:
for name in Amel_fa.keys():
    if name.startswith("CM"):
        print(f"{name}: {len(Amel_fa[name])}")

CM009931.2: 27754200
CM009932.2: 16089512
CM009933.2: 13619445
CM009934.2: 13404451
CM009935.2: 13896941
CM009936.2: 17789102
CM009937.2: 14198698
CM009938.2: 12717210
CM009939.2: 12354651
CM009940.2: 12360052
CM009941.2: 16352600
CM009942.2: 11514234
CM009943.2: 11279722
CM009944.2: 10670842
CM009945.2: 9534514
CM009946.2: 7238532
CM009947.2: 16343

CM009947.2 is mito

In [7]:
import pandas as pd

Amel_txinfo = pd.read_csv("./metadata/Amel_txinfo.tsv", sep = "\t")
Amel_txinfo

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,gene_biotype,gene_name,gene_source,protein_id,transcript_biotype,transcript_name,transcript_source,ensembl_canonical,seleno
0,XM_006559882,LOC100576147,CM009931.2,+,1,4102,1278,520,2304,protein_coding,NaN,RefSeq,XP_006559945,protein_coding,NaN,RefSeq,True,False
1,XM_006561922,LOC100577342,CM009931.2,+,4,1173,825,192,156,protein_coding,NaN,RefSeq,XP_006561985,protein_coding,NaN,RefSeq,True,False
2,XM_026445023,LOC551556,CM009931.2,-,4,1369,1209,122,38,protein_coding,NaN,RefSeq,XP_026300808,protein_coding,NaN,RefSeq,True,False
3,XM_006563296,LOC727596,CM009931.2,+,4,1065,807,199,59,protein_coding,NaN,RefSeq,XP_006563359,protein_coding,NaN,RefSeq,True,False
4,XM_026446341,LOC727596,CM009931.2,+,5,1018,807,152,59,protein_coding,NaN,RefSeq,XP_026302126,protein_coding,NaN,RefSeq,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28405,XR_003306401,LOC113219356,QIUM02000210.1,-,1,153,0,0,0,rRNA,NaN,RefSeq,NaN,rRNA,NaN,RefSeq,True,False
28406,LOC113219357_df_pt,LOC113219357,QIUM02000210.1,-,1,3520,0,0,0,pseudogene,NaN,RefSeq,NaN,pseudogene,NaN,RefSeq,True,False
28407,XR_003306469,LOC113219387,QIUM02000211.1,+,1,3962,0,0,0,rRNA,NaN,RefSeq,NaN,rRNA,NaN,RefSeq,True,False
28408,XM_026445952,LOC113219358,QIUM02000217.1,-,2,888,504,0,384,protein_coding,NaN,RefSeq,XP_026301737,protein_coding,NaN,RefSeq,True,False
28409,XR_003306369,LOC113219341,QIUM02000219.1,+,1,1923,0,0,0,rRNA,NaN,RefSeq,NaN,rRNA,NaN,RefSeq,True,False

In [12]:
mito_txinfo = Amel_txinfo[Amel_txinfo["chrom"] == "CM009947.2"]
mito_txinfo

,tx_name,gene_id,chrom,strand,nexon,tx_len,cds_len,utr5_len,utr3_len,gene_biotype,gene_name,gene_source,protein_id,transcript_biotype,transcript_name,transcript_source,ensembl_canonical,seleno
28152,NC_001566.1:6734..6802,NC_001566.1:6734..6802_df_g,CM009947.2,+,1,69,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28153,GeneID_807695_df_mr,GeneID_807695,CM009947.2,+,1,1566,1566,0,0,protein_coding,COX1,RefSeq,NP_008083,protein_coding,COX1_df_mr,RefSeq,True,False
28154,GeneID_807696_df_mr,GeneID_807696,CM009947.2,+,1,681,681,0,0,protein_coding,ATP6,RefSeq,NP_008086,protein_coding,ATP6_df_mr,RefSeq,True,False
28155,NC_001566.1:6119..6184,NC_001566.1:6119..6184_df_g,CM009947.2,+,1,66,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28156,GeneID_807699_df_mr,GeneID_807699,CM009947.2,+,1,159,159,0,0,protein_coding,ATP8,RefSeq,NP_008085,protein_coding,ATP8_df_mr,RefSeq,True,False
28157,GeneID_807700_df_mr,GeneID_807700,CM009947.2,+,1,678,678,0,0,protein_coding,COX2,RefSeq,NP_008084,protein_coding,COX2_df_mr,RefSeq,True,False
28158,GeneID_807690_df_mr,GeneID_807690,CM009947.2,+,1,780,780,0,0,protein_coding,COX3,RefSeq,NP_008087,protein_coding,COX3_df_mr,RefSeq,True,False
28159,GeneID_807702_df_mr,GeneID_807702,CM009947.2,-,1,1344,1344,0,0,protein_coding,ND4,RefSeq,NP_008090,protein_coding,ND4_df_mr,RefSeq,True,False
28160,GeneID_807693_df_mr,GeneID_807693,CM009947.2,+,1,1152,1152,0,0,protein_coding,CYTB,RefSeq,NP_008093,protein_coding,CYTB_df_mr,RefSeq,True,False
28161,NC_001566.1:14732..15517,NC_001566.1:14732..15517_df_g,CM009947.2,-,1,786,0,0,0,rRNA,NaN,RefSeq,NaN,rRNA,NaN,RefSeq,True,False
28162,NC_001566.1:221..286,NC_001566.1:221..286_df_g,CM009947.2,+,1,66,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28163,NC_001566.1:13220..13290,NC_001566.1:13220..13290_df_g,CM009947.2,-,1,71,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28164,NC_001566.1:14662..14731,NC_001566.1:14662..14731_df_g,CM009947.2,-,1,70,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28165,NC_001566.1:1592..1659,NC_001566.1:1592..1659_df_g,CM009947.2,-,1,68,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28166,NC_001566.1:3355..3424,NC_001566.1:3355..3424_df_g,CM009947.2,+,1,70,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28167,NC_001566.1:13291..14661,NC_001566.1:13291..14661_df_g,CM009947.2,-,1,1371,0,0,0,rRNA,NaN,RefSeq,NaN,rRNA,NaN,RefSeq,True,False
28168,GeneID_807692_df_mr,GeneID_807692,CM009947.2,-,1,918,918,0,0,protein_coding,ND1,RefSeq,NP_008094,protein_coding,ND1_df_mr,RefSeq,True,False
28169,NC_001566.1:10365..10432,NC_001566.1:10365..10432_df_g,CM009947.2,-,1,68,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28170,NC_001566.1:1..66,NC_001566.1:1..66_df_g,CM009947.2,+,1,66,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28171,NC_001566.1:116..178,NC_001566.1:116..178_df_g,CM009947.2,+,1,63,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28172,NC_001566.1:296..358,NC_001566.1:296..358_df_g,CM009947.2,+,1,63,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28173,GeneID_807698_df_mr,GeneID_807698,CM009947.2,-,1,1665,1665,0,0,protein_coding,ND5,RefSeq,NP_008089,protein_coding,ND5_df_mr,RefSeq,True,False
28174,NC_001566.1:12201..12267,NC_001566.1:12201..12267_df_g,CM009947.2,+,1,67,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28175,NC_001566.1:433..501,NC_001566.1:433..501_df_g,CM009947.2,+,1,69,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28176,GeneID_807701_df_mr,GeneID_807701,CM009947.2,+,1,1002,1002,0,0,protein_coding,ND2,RefSeq,NP_008082,protein_coding,ND2_df_mr,RefSeq,True,False
28177,NC_001566.1:8557..8624,NC_001566.1:8557..8624_df_g,CM009947.2,-,1,68,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28178,GeneID_807691_df_mr,GeneID_807691,CM009947.2,+,1,354,354,0,0,protein_coding,ND3,RefSeq,NP_008088,protein_coding,ND3_df_mr,RefSeq,True,False
28179,NC_001566.1:360..429,NC_001566.1:360..429_df_g,CM009947.2,+,1,70,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28180,NC_001566.1:10267..10344,NC_001566.1:10267..10344_df_g,CM009947.2,+,1,78,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28181,NC_001566.1:4370..4438,NC_001566.1:4370..4438_df_g,CM009947.2,+,1,69,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28182,NC_001566.1:1503..1571,NC_001566.1:1503..1571_df_g,CM009947.2,-,1,69,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28183,NC_001566.1:4294..4362,NC_001566.1:4294..4362_df_g,CM009947.2,+,1,69,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28184,NC_001566.1:6572..6638,NC_001566.1:6572..6638_df_g,CM009947.2,-,1,67,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28185,GeneID_807697_df_mr,GeneID_807697,CM009947.2,+,1,504,504,0,0,protein_coding,ND6,RefSeq,NP_008092,protein_coding,ND6_df_mr,RefSeq,True,False
28186,GeneID_807694_df_mr,GeneID_807694,CM009947.2,-,1,264,264,0,0,protein_coding,ND4L,RefSeq,NP_008091,protein_coding,ND4L_df_mr,RefSeq,True,False
28187,NC_001566.1:6810..6878,NC_001566.1:6810..6878_df_g,CM009947.2,-,1,69,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False
28188,NC_001566.1:1722..1793,NC_001566.1:1722..1793_df_g,CM009947.2,+,1,72,0,0,0,tRNA,NaN,RefSeq,NaN,tRNA,NaN,RefSeq,True,False

In [26]:
mito_txinfo_geneid = set(mito_txinfo["gene_id"].to_list())
mito_txinfo_geneid

{'GeneID_807690',
 'GeneID_807691',
 'GeneID_807692',
 'GeneID_807693',
 'GeneID_807694',
 'GeneID_807695',
 'GeneID_807696',
 'GeneID_807697',
 'GeneID_807698',
 'GeneID_807699',
 'GeneID_807700',
 'GeneID_807701',
 'GeneID_807702',
 'NC_001566.1:1..66_df_g',
 'NC_001566.1:10267..10344_df_g',
 'NC_001566.1:10365..10432_df_g',
 'NC_001566.1:116..178_df_g',
 'NC_001566.1:12201..12267_df_g',
 'NC_001566.1:13220..13290_df_g',
 'NC_001566.1:13291..14661_df_g',
 'NC_001566.1:14662..14731_df_g',
 'NC_001566.1:14732..15517_df_g',
 'NC_001566.1:1503..1571_df_g',
 'NC_001566.1:1592..1659_df_g',
 'NC_001566.1:1722..1793_df_g',
 'NC_001566.1:221..286_df_g',
 'NC_001566.1:296..358_df_g',
 'NC_001566.1:3355..3424_df_g',
 'NC_001566.1:360..429_df_g',
 'NC_001566.1:4294..4362_df_g',
 'NC_001566.1:433..501_df_g',
 'NC_001566.1:4370..4438_df_g',
 'NC_001566.1:6119..6184_df_g',
 'NC_001566.1:6572..6638_df_g',
 'NC_001566.1:6734..6802_df_g',
 'NC_001566.1:6810..6878_df_g',
 'NC_001566.1:8557..8624_df_g'}

In [13]:
import scanpy as sc

F1_adata = sc.read_10x_h5("./h5_from_fastq2matrix/F1.h5")

/home/liuzhiyu/Software/miniconda3/envs/downstream_analysis/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/liuzhiyu/Software/miniconda3/envs/downstream_analysis/lib/python3.10/site-packages/anndata/_core/anndata.py:1758: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [27]:
F1_geneids = set(F1_adata.var["gene_ids"].to_list())
F1_geneids

{'LOC100576841',
 'LOC726316',
 'LOC408712',
 'LOC727346',
 'LOC724578',
 'LOC552228',
 'LOC102656568',
 'LOC410235',
 'LOC552318',
 'LOC412079',
 'LOC102653753',
 'LOC726265',
 'LOC100577801',
 'LOC102656337',
 'LOC102656016',
 'LOC102656116',
 'LOC409642',
 'LOC409741',
 'LOC102655432',
 'LOC100578276',
 'LOC107965291',
 'LOC100577620',
 'LOC102656737',
 'LOC100578839',
 'LOC412194',
 'LOC725167',
 'GeneID_412427',
 'LOC724924',
 'LOC726521',
 'LOC107964635',
 'LOC409142',
 'LOC100578367',
 'LOC551969',
 'LOC551204',
 'LOC409107',
 'LOC409089',
 'LOC552374',
 'LOC113218526',
 'LOC113219268',
 'LOC102654369',
 'GeneID_725168',
 'LOC551461',
 'LOC107965146',
 'LOC410819',
 'LOC725028',
 'LOC102653960',
 'LOC552412',
 'LOC102654231',
 'LOC409463',
 'LOC727618',
 'LOC113219066',
 'LOC724860',
 'LOC100576473',
 'LOC725699',
 'LOC726636',
 'LOC409643',
 'LOC409199',
 'LOC100576717',
 'LOC102654740',
 'LOC100576644',
 'GeneID_100577309',
 'GeneID_406133',
 'GeneID_411635',
 'LOC412828',
 'LOC410274',
 'LOC107964899',
 'LOC412391',
 'LOC410320',
 'LOC408633',
 'LOC409584',
 'LOC411013',
 'GeneID_409012',
 'LOC724117',
 'LOC725408',
 'LOC412127',
 'LOC552679',
 'LOC100578375',
 'LOC408966',
 'LOC724665',
 'LOC726859',
 'LOC100577017',
 'LOC410535',
 'LOC552099',
 'LOC100577986',
 'LOC100578670',
 'LOC408283',
 'LOC113218520',
 'LOC409286',
 'LOC409863',
 'LOC410361',
 'LOC724294',
 'LOC725316',
 'LOC551446',
 'LOC551363',
 'GeneID_807693',
 'LOC552092',
 'LOC113219125',
 'LOC411023',
 'LOC724692',
 'LOC113218657',
 'LOC726350',
 'LOC411433',
 'LOC726766',
 'LOC411167',
 'LOC408774',
 'LOC107964343',
 'LOC113219405',
 'LOC725516',
 'LOC113219163',
 'LOC410237',
 'LOC724193',
 'LOC102656130',
 'LOC725641',
 'LOC102655045',
 'LOC725595',
 'LOC100577573',
 'LOC726303',
 'LOC725057',
 'LOC412284',
 'LOC552200',
 'LOC412465',
 'LOC107964020',
 'LOC552647',
 'LOC726826',
 'LOC413165',
 'LOC100578233',
 'LOC113219046',
 'LOC107965697',
 'LOC102655173',
 'LOC413384',
 'LOC413794',
 'LOC411218',
 'LOC107964072',
 'LOC100577749',
 'LOC725467',
 'LOC724997',
 'LOC724295',
 'LOC410363',
 'LOC552766',
 'LOC726854',
 'LOC726912',
 'LOC100576843',
 'LOC725707',
 'LOC727278',
 'LOC725527',
 'LOC551249',
 'LOC413966',
 'LOC408917',
 'LOC107965353',
 'LOC413755',
 'LOC725419',
 'LOC724312',
 'LOC726099',
 'LOC107964039',
 'LOC408343',
 'LOC113219027',
 'LOC113219310',
 'LOC551831',
 'LOC413447',
 'LOC552816',
 'LOC725947',
 'GeneID_409224',
 'LOC410986',
 'LOC724651',
 'LOC100578011',
 'LOC411732',
 'LOC411555',
 'LOC113219344',
 'LOC552223',
 'LOC411458',
 'LOC724296',
 'LOC102654160',
 'LOC100579058',
 'LOC411753',
 'LOC551073',
 'LOC100576886',
 'LOC411662',
 'LOC102654810',
 'LOC409383',
 'LOC102653975',
 'LOC102654462',
 'LOC551211',
 'LOC409955',
 'LOC100576986',
 'LOC409976',
 'LOC409047',
 'LOC100577143',
 'LOC406114',
 'LOC724553',
 'LOC100576908',
 'LOC410406',
 'LOC551806',
 'LOC107964964',
 'LOC113218663',
 'LOC724172',
 'LOC410792',
 'LOC552178',
 'LOC411799',
 'LOC411757',
 'GeneID_411899',
 'LOC408660',
 'LOC100578855',
 'LOC100576529',
 'LOC413430',
 'LOC410769',
 'LOC100578865',
 'LOC551701',
 'LOC413133',
 'LOC107963982',
 'LOC412824',
 'LOC552047',
 'LOC100578046',
 'LOC413924',
 'LOC727630',
 'GeneID_726057',
 'LOC727299',
 'LOC412529',
 'LOC102656082',
 'LOC113218571',
 'LOC726692',
 'LOC411507',
 'LOC410340',
 'LOC409639',
 'GeneID_544670',
 'LOC725904',
 'LOC725796',
 'LOC551465',
 'LOC412303',
 'LOC409168',
 'LOC102653733',
 'LOC113219250',
 'LOC113218542',
 'LOC411807',
 'LOC551571',
 'LOC113219037',
 'LOC413534',
 'LOC724831',
 'LOC100576272',
 'LOC727420',
 'LOC411657',
 'LOC113219139',
 'LOC409628',
 'LOC551936',
 'LOC409543',
 'GeneID_725932',
 'LOC552586',
 'LOC552634',
 'LOC726776',
 'LOC726592',
 'LOC409688',
 'LOC102654197',
 'LOC412996',
 'LOC102655787',
 'LOC113218528',
 'LOC552375',
 'LOC725974',
 'LOC102655689',
 'LOC411805',
 'LOC408302',
 'LOC724616',
 'LOC102654837',
 'LOC409924',
 'LOC100576745',
 'LOC552237',
 'LOC102656183',
 'LOC409755',
 'LOC408710',
 'LOC552433',
 'LOC102656134',
 'LOC725756',
 'LOC107965272',
 'LOC100578697',
 'LOC409766',
 'LOC725795',
 'LOC107966025',
 'LOC107965775',
 'LOC552472',
 'LOC410979',
 'LOC107966099',
 'LOC552794',
 'LOC413980',
 'LOC410752',
 'LOC113218553',
 'LOC113218559',
 'LOC102654690',
 'LOC102654988',
 'LOC410041',
 'LOC413930',
 'LOC102655280',
 'LOC410266',
 'LOC413551',
 'LOC107964774',
 'LOC552089',
 'LOC724965',
 'LOC727375',
 'LOC102655922',
 'LOC412217',
 'LOC100576555',
 'LOC724976',
 'LOC408335',
 'LOC727520',
 'LOC100576839',
 'LOC100578860',
 'LOC409007',
 'LOC412913',
 'LOC413331',
 'LOC727106',
 'LOC409588',
 'GeneID_727204',
 'LOC551256',
 'LOC102656798',
 'LOC100577382',
 'LOC102655371',
 'LOC724157',
 'LOC413891',
 'LOC100577365',
 'LOC551966',
 'LOC413112',
 'LOC412789',
 'LOC550698',
 'LOC412328',
 'LOC724879',
 'LOC409394',
 'LOC409522',
 'LOC102654832',
 'LOC550706',
 'LOC409206',
 'LOC726315',
 'LOC412697',
 'LOC113219209',
 'LOC409836',
 'LOC552094',
 'LOC552776',
 'LOC411573',
 'LOC102656404',
 'LOC113218726',
 'LOC100579054',
 'LOC100578587',
 'LOC552736',
 'LOC725899',
 'LOC410495',
 'LOC412116',
 'GeneID_412304',
 'LOC725905',
 'LOC726389',
 'LOC100578464',
 'LOC551731',
 'LOC551950',
 'LOC726977',
 'LOC726551',
 'LOC724710',
 'LOC551785',
 'LOC725380',
 'LOC100577875',
 'LOC102656905',
 'LOC100577748',
 'LOC100577341',
 'LOC409552',
 'LOC102655522',
 'LOC409626',
 'LOC409603',
 'LOC726997',
 'LOC726397',
 'LOC412688',
 'LOC726657',
 'LOC100577696',
 'LOC100578177',
 'LOC724393',
 'GeneID_412202',
 'LOC100576182',
 'LOC100578853',
 'LOC726436',
 'LOC724552',
 'LOC113218591',
 'LOC410514',
 'LOC412728',
 'LOC724270',
 'LOC100577348',
 'LOC107964944',
 'LOC551914',
 'GeneID_409948',
 'LOC100578586',
 'LOC410042',
 'LOC726000',
 'LOC724873',
 'LOC412085',
 'LOC113218895',
 'LOC100576853',
 'LOC107965323',
 'LOC408958',
 'LOC100578119',
 'LOC102653901',
 'LOC100576808',
 'LOC413256',
 'LOC100576504',
 'LOC727035',
 'LOC100188940',
 'LOC409549',
 'LOC726060',
 'LOC727415',
 'LOC100577936',
 'LOC408965',
 'LOC100578608',
 'LOC107965520',
 'LOC102654924',
 'LOC726149',
 'LOC410424',
 'LOC412665',
 'LOC726110',
 'LOC410339',
 'LOC726096',
 'LOC552055',
 'LOC726284',
 'LOC113218519',
 'LOC107963972',
 'LOC100578355',
 'LOC551976',
 'LOC100578446',
 'LOC113219210',
 'LOC726133',
 'LOC410109',
 'LOC409818',
 'LOC100576288',
 'LOC102653988',
 'GeneID_406090',
 'LOC412104',
 'LOC724548',
 'GeneID_100049571',
 'LOC724593',
 'LOC413108',
 'LOC727271',
 'LOC727007',
 'LOC409792',
 'LOC724515',
 'LOC113218792',
 'LOC102654791',
 'LOC102654107',
 'LOC726537',
 'LOC724238',
 'LOC726054',
 'LOC102654245',
 'LOC102656934',
 'LOC113219365',
 'LOC725261',
 'LOC413106',
 'LOC726494',
 'LOC412363',
 'LOC552600',
 'LOC100578404',
 'LOC107965266',
 'LOC725780',
 'LOC412550',
 'LOC413523',
 'LOC726280',
 'LOC113218835',
 'LOC412459',
 'LOC552429',
 'LOC409207',
 'LOC552117',
 'LOC726746',
 'LOC410357',
 'LOC100578835',
 'LOC724343',
 'LOC551454',
 'LOC102655786',
 'LOC100577209',
 'LOC411563',
 'LOC409861',
 'LOC724352',
 'LOC107964569',
 'LOC102656138',
 'LOC725281',
 'LOC724636',
 'LOC100577766',
 'LOC413562',
 'LOC102655709',
 'LOC413471',
 'LOC102654144',
 'LOC413946',
 'LOC102655847',
 'LOC410317',
 'LOC413166',
 'LOC409734',
 'LOC413829',
 'LOC552619',
 'LOC551021',
 'LOC113219424',
 'LOC408458',
 'LOC409722',
 'LOC725818',
 'LOC551405',
 'LOC725498',
 'LOC113218780',
 'LOC408986',
 'LOC412230',
 'LOC551489',
 'LOC408779',
 'LOC107965279',
 'LOC409999',
 'LOC102654662',
 'LOC413366',
 'LOC409505',
 'LOC100577409',
 'LOC100577742',
 'LOC102655819',
 'LOC727306',
 'LOC411172',
 'LOC102654439',
 'LOC413557',
 'LOC113218610',
 'LOC113218570',
 'LOC102654592',
 'LOC413006',
 'LOC727166',
 'LOC107964224',
 'LOC413350',
 'GeneID_724143',
 'LOC102654006',
 'LOC726251',
 'LOC552083',
 'LOC412681',
 'LOC113219156',
 'LOC102653601',
 'LOC102654259',
 'LOC552108',
 'LOC413510',
 'LOC409533',
 'LOC102654841',
 'LOC412608',
 'LOC100577942',
 'LOC100576176',
 'LOC412890',
 'LOC410226',
 'LOC113219104',
 'LOC100578131',
 'LOC410387',
 'LOC411496',
 'LOC409125',
 'LOC113218598',
 'LOC724368',
 'LOC408346',
 'LOC411306',
 'LOC725288',
 'LOC412454',
 'LOC411524',
 'LOC412360',
 'LOC413672',
 'LOC100578006',
 'LOC503505',
 'LOC100577444',
 'LOC552497',
 'LOC102655507',
 'LOC724370',
 'GeneID_724978ipped-B',
 'LOC107965577',
 'LOC413486',
 'LOC411154',
 'LOC411585',
 'LOC410410',
 'LOC102655174',
 'LOC413674',
 'LOC408525',
 'LOC113219068',
 'LOC107964850',
 'LOC725961',
 'LOC725889',
 'LOC413907',
 'LOC410799',
 'LOC724798',
 'LOC725619',
 'LOC413683',
 'LOC724264',
 'LOC100576528',
 'LOC551682',
 'LOC409371',
 'LOC726373',
 'LOC409548',
 'LOC409981',
 'LOC113219406',
 'LOC409321',
 'LOC100578779',
 'LOC726080',
 'GeneID_726567',
 'LOC552672',
 'LOC100577135',
 'LOC727153',
 'LOC107965414',
 'LOC409179',
 'LOC551447',
 'GeneID_725259',
 'LOC724760',
 'LOC100578262',
 'LOC725887',
 'LOC552769',
 'LOC107963968',
 'LOC100576817',
 'LOC100576640',
 'LOC726833',
 'LOC409363',
 'LOC413489',
 'LOC727522',
 'LOC727432',
 'LOC409473',
 'LOC409202',
 'LOC413936',
 'LOC100579055',
 'LOC410985',
 'LOC551602',
 'LOC552246',
 'LOC724648',
 'LOC102655798',
 'LOC107964069',
 'LOC411227',
 'LOC100576677',
 'LOC551486',
 'LOC411955',
 'LOC413873',
 'GeneID_412632',
 'LOC550935',
 'LOC107964008',
 'LOC102654696',
 'LOC102654623',
 'LOC100577192',
 'LOC408267',
 'LOC725021',
 'LOC100578484',
 'LOC409157',
 'GeneID_406141',
 'LOC100576975',
 'LOC100577541',
 'LOC410009',
 'LOC551560',
 'LOC726244',
 'LOC102654682',
 'LOC102656282',
 'LOC413210',
 'LOC100578751',
 'LOC107964608',
 'LOC113218525',
 'LOC102656218',
 'LOC113218587',
 'LOC726250',
 'LOC107964158',
 'LOC410601',
 'LOC408572',
 'LOC552726',
 'LOC724286',
 'LOC409162',
 'LOC551740',
 'LOC410261',
 'LOC100577307',
 'LOC113218871',
 'LOC551896',
 'LOC409984',
 'LOC726297',
 'LOC408564',
 'LOC725973',
 'LOC412191',
 'GeneID_726087',
 'LOC725654',
 'LOC113218560',
 'LOC100577493',
 'LOC725742',
 'LOC725147',
 'LOC725220',
 'LOC408951',
 'LOC412573',
 'GeneID_550961',
 'LOC551739',
 'LOC107964015',
 'LOC409082',
 'LOC551203',
 'LOC409282',
 'LOC409908',
 'LOC551948',
 'LOC413885',
 'LOC100576082',
 'LOC724656',
 'LOC102654380',
 'LOC552395',
 'LOC413207',
 'LOC724867',
 'LOC551835',
 'LOC413774',
 'LOC113219126',
 'LOC100576554',
 'LOC726792',
 'LOC552153',
 'LOC102654435',
 'LOC551986',
 'LOC107964976',
 'LOC411058',
 'LOC725151',
 'LOC113218750',
 'LOC100578834',
 'LOC413299',
 'LOC102656151',
 'LOC411649',
 'LOC408876',
 'LOC102653798',
 'LOC411188',
 'LOC107965308',
 'LOC113219220',
 'LOC413619',
 'LOC113219282',
 'LOC551582',
 'LOC113218879',
 'LOC100576242',
 'LOC725405',
 'LOC100577584',
 'LOC726655',
 'LOC102655971',
 'LOC102656440',
 'LOC113219182',
 'LOC724156',
 'LOC724517',
 'LOC100576132',
 'LOC113219111',
 'LOC551584',
 'LOC100576657',
 'LOC412813',
 'LOC724475',
 'LOC725401',
 'LOC724864',
 'LOC100859932',
 'LOC726205',
 'LOC551918',
 'LOC107964219',
 'LOC727234',
 'LOC409129',
 'LOC409255',
 'LOC102655285',
 'LOC725687',
 'LOC726653',
 'GeneID_100359410',
 'LOC102655409',
 'LOC727127',
 'GeneID_410435',
 'LOC100577919',
 'LOC409993',
 'LOC725225',
 'LOC413170',
 'LOC411536',
 'LOC100578502',
 'LOC102656732',
 'LOC551803',
 'LOC412245',
 'LOC412103',
 'GeneID_409376',
 'LOC113218949',
 'LOC100578454',
 'LOC113219162',
 'LOC409634',
 'LOC727649',
 'LOC100577094',
 'LOC410968',
 'LOC102653928',
 'LOC725675',
 'LOC408789',
 'LOC725824',
 'LOC413032',
 'LOC412222',
 'LOC113218745',
 'LOC100578821',
 'LOC412355',
 'LOC410456',
 'LOC409985',
 'LOC102656230',
 'LOC411387',
 'LOC107964592',
 'GeneID_100578520',
 'LOC408836',
 'LOC727324',
 'GeneID_413894',
 'LOC102655674',
 'LOC411533',
 'LOC552019',
 'LOC409487',
 'LOC410245',
 'LOC727229',
 'LOC725941',
 'LOC412000',
 'LOC100577146',
 'LOC413242',
 'LOC412513',
 'LOC100577489',
 'LOC102654158',
 'LOC102655251',
 'LOC412349',
 'LOC726394',
 'LOC100576679',
 'LOC410726',
 'LOC551596',
 'LOC412644',
 'LOC100577026',
 'LOC100576093',
 'LOC411985',
 'LOC411290',
 'LOC409186',
 'LOC551718',
 'LOC100576282',
 'LOC408426',
 'LOC413186',
 'LOC100577723',
 'LOC724750',
 'LOC413409',
 'LOC412593',
 'LOC724933',
 'LOC725099',
 'LOC725128',
 'LOC552091',
 'LOC107966040',
 'LOC410600',
 'LOC724560',
 'LOC408863',
 'LOC102656292',
 'LOC102654674',
 'LOC410718',
 'LOC113219262',
 'LOC725279',
 'LOC410365',
 'LOC102653993',
 'LOC100577548',
 'LOC725524',
 'LOC724998',
 'LOC107966054',
 'LOC102654113',
 'LOC725786',
 'LOC107966088',
 'LOC726332',
 'LOC410533',
 'GeneID_406083',
 'LOC552829',
 'LOC725711',
 'LOC100577293',
 'LOC102654315',
 'LOC113219033',
 'LOC412024',
 'LOC725247',
 'LOC410223',
 'LOC410922',
 'LOC408543',
 'LOC552563',
 'LOC113219015',
 'LOC409485',
 'LOC551974',
 'LOC107964189',
 'LOC413592',
 'LOC725826',
 'LOC726806',
 'LOC113218715',
 'LOC552353',
 'LOC102655281',
 'LOC102656302',
 'LOC412944',
 'LOC100576099',
 'LOC102653778',
 'LOC100578966',
 'LOC411613',
 'LOC100577938',
 'LOC411651',
 'LOC551102',
 'LOC100577128',
 'LOC724842',
 'LOC413146',
 'LOC725992',
 'LOC100576773',
 'LOC726673',
 'LOC409523',
 'LOC724348',
 'LOC410246',
 'LOC727642',
 'LOC113218639',
 'LOC412296',
 'LOC726721',
 'LOC107964045',
 'LOC107964134',
 'LOC102654398',
 'LOC102654939',
 'LOC102655080',
 'LOC408578',
 'LOC100576733',
 'LOC100577422',
 'LOC100577346',
 'LOC725383',
 'LOC107964237',
 'LOC551690',
 'LOC412626',
 'GeneID_100578142',
 'LOC100578716',
 'LOC410925',
 'LOC107965198',
 'LOC725629',
 'LOC727331',
 'LOC100577629',
 'LOC102655670',
 'LOC113218772',
 'LOC551595',
 'LOC102655453',
 'LOC408908',
 'LOC410172',
 'LOC113218998',
 'LOC102655843',
 'LOC410487',
 'LOC413183',
 'LOC724899',
 'LOC107965670',
 'LOC552833',
 'LOC408883',
 'LOC410863',
 'LOC100577188',
 'LOC413390',
 'LOC100577932',
 'LOC100578666',
 'LOC107964312',
 'LOC113219069',
 'LOC413099',
 'LOC102655353',
 'LOC552534',
 'LOC724685',
 'GeneID_406153',
 'LOC100578329',
 'LOC113218752',
 'LOC725079',
 'LOC102656705',
 'LOC409316',
 'LOC100576224',
 'LOC411359',
 'LOC413943',
 'GeneID_100576395',
 'LOC551763',
 'LOC100578727',
 'GeneID_100576714',
 'LOC552471',
 'LOC102656021',
 'LOC113219117',
 'LOC408842',
 'LOC113219364',
 'LOC107964990',
 'LOC410851',
 'LOC724541',
 'LOC724483',
 'LOC413919',
 'LOC725578',
 'LOC102655237',
 'LOC550818',
 'LOC413141',
 'LOC411270',
 'LOC725831',
 'LOC412314',
 'LOC113218937',
 'LOC411871',
 'LOC102654469',
 'LOC113218863',
 'LOC552515',
 'LOC727192',
 'LOC724509',
 'LOC552193',
 'LOC725362',
 'LOC726758',
 'LOC724680',
 'LOC102654856',
 'LOC413649',
 'LOC411599',
 'LOC551609',
 'LOC107965147',
 'LOC409164',
 'LOC724170',
 'LOC551205',
 'LOC551301',
 'LOC413264',
 'LOC412108',
 'LOC113218967',
 'LOC413065',
 'LOC113218768',
 'LOC100578609',
 'LOC551957',
 'GeneID_494523',
 'LOC413948',
 'LOC411627',
 'LOC102653904',
 'LOC100577164',
 'LOC107965624',
 'LOC726028',
 'LOC552331',
 'LOC100578995',
 'GeneID_408764',
 'LOC113218708',
 'LOC113218612',
 'LOC113219086',
 'LOC552780',
 'LOC411916',
 'LOC725938',
 'LOC409983',
 'LOC726619',
 'LOC411837',
 'LOC551464',
 'LOC551296',
 'LOC726147',
 'LOC102654896',
 ...}

In [30]:
print(len(mito_txinfo_geneid & F1_geneids))
print(mito_txinfo_geneid & F1_geneids)

13
{'GeneID_807694', 'GeneID_807697', 'GeneID_807691', 'GeneID_807700', 'GeneID_807690', 'GeneID_807701', 'GeneID_807696', 'GeneID_807695', 'GeneID_807693', 'GeneID_807698', 'GeneID_807692', 'GeneID_807702', 'GeneID_807699'}